/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Mementos.TabuleiroMemento;
import Prototype.Peca;
import States.Tabuleiro.TabuleiroFinalizado;
import States.Tabuleiro.TabuleiroIniciado;
import States.Tabuleiro.TabuleiroState;
import Strategies.JogadorStrategy;
import Strategies.TipoJogador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;


/**
 *
 * @author Junnyor
 */
public class TabuleiroGUI extends javax.swing.JFrame {
    
    private Tabuleiro tabuleiro;
    
    public Botao[][] botoes;
    
    static TabuleiroGUI tabuleiroGUI;
    
    private JogadorStrategy jogador;
    
    
    /**
     * Creates new form Tabuleiro
     * @param tabuleiro
     * @param botoes
     */
    public TabuleiroGUI(Tabuleiro tabuleiro, Botao[][] botoes) {
        initComponents();
        this.botoes = botoes;
        this.tabuleiro = tabuleiro;
        
        TabuleiroIniciado tabuleiroIniciado = new TabuleiroIniciado();        
        this.tabuleiro.setEstado(tabuleiroIniciado);
        this.tabuleiro.iniciar();
        
        //Iniciando com jogador do tipo X
        TipoJogador tipoJogador = TipoJogador.values()[0];
        this.jogador = tipoJogador.obterJogador();
        
        this.lbJogador.setText(this.jogador.getTipo().getNome());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbJogador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbJogador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbJogador.setText("X");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Jogador");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar Jogo");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbJogador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar))
                    .addComponent(btnFinalizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnRestaurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador)
                    .addComponent(jLabel2))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        TabuleiroFinalizado tabuleiroFinalizado = new TabuleiroFinalizado();        
        tabuleiroGUI.getTabuleiro().setEstado(tabuleiroFinalizado);
        tabuleiroGUI.getTabuleiro().finalizar();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                tabuleiroGUI = new TabuleiroGUI(new Tabuleiro(), new Botao[3][3]);
                tabuleiroGUI.setVisible(true);
                tabuleiroGUI.desenhar();              
            }
        });
    }

    public Tabuleiro getTabuleiro() {
        return tabuleiro;
    }

    public void setTabuleiro(Tabuleiro tabuleiro) {
        this.tabuleiro = tabuleiro;
    }
    
    private void desenhar() {
        int x = 0, y = 0;   
        for(int i = 0; i < 3; i++) {
            for(int j = 0; j < 3; j++) {
                Botao botao = new Botao();
                botao.setLinha(i);
                botao.setColuna(j);
                botao.setName("peca"+i+""+j);
                //botao.setText("peca"+i+""+j);
                botao.enable(true);
                botao.setBounds(x, y, 70, 70);
                botao.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        botaoOnClick(evt, botao.getLinha(), botao.getColuna());
                    }
                });
                this.botoes[i][j] = botao;
                this.jPanel1.add(botao);
                x += 100;
            }
            y += 100;
            x = 0;
        }        
    }
    
    
    public void botaoOnClick(ActionEvent ae, int linha, int coluna) {
        
        TipoJogador tipoJogador = null;
        
        //Verifico se não existe uma peça no botão
        if(this.botoes[linha][coluna].getPeca() == null) {
            this.botoes[linha][coluna].setPeca(this.jogador.getTipo());
            this.botoes[linha][coluna].setText(this.jogador.getTipo().getNome());

            if(this.jogador.getTipo().getNome().equals("X")) {
                tipoJogador = TipoJogador.values()[1];
            } else {
                tipoJogador = TipoJogador.values()[0];
            }

        }
        
        
        int i = 0;
        boolean finalizou = false;
        for(int j = 0; j < 3; j++) {
            if(this.botoes[i][j].getText().equals("X")) {
                finalizou = true;
            } else {
                finalizou = false;
                break;
            }
        }
        
        System.out.println(""+finalizou);
        
        this.jogador = tipoJogador.obterJogador();
        this.lbJogador.setText(this.jogador.getTipo().getNome());

            
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbJogador;
    // End of variables declaration//GEN-END:variables
}
